name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Deno environment
    - uses: denolib/setup-deno@v2.0.0

    - uses: actions/checkout@v2

    - name: Deno version
      run: deno --version
    
    - name: Deno test
      run: deno -A test
